### ISSUE TITLE
Installation requires patching cabal file

### ISSUE THREAD

**Issue by domoritz** [egnwd/pingo#1]
I'd like to use the package but don't have Haskell experience. What's the easiest way to get a package for MacOS?

```
$ cabal install                                                                                                                    Resolving dependencies...
cabal: Could not resolve dependencies:
trying: pingo-0.3.0.0 (user goal)
next goal: base (dependency of pingo-0.3.0.0)
rejecting: base-4.11.0.0/installed-4.1... (conflict: pingo => base>=4.8 &&
<4.10)
rejecting: base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0,
base-4.9.0.0, base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2,
base-4.7.0.1, base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0,
base-4.5.0.0, base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0,
base-4.2.0.2, base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0,
base-3.0.3.2, base-3.0.3.1 (constraint from non-upgradeable package requires
installed instance)
fail (backjumping, conflict set: base, pingo)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, pingo
```

**Comment by domoritz** [comment]
It looks like I can compile when I replace `base >=4.8 && <4.10` with `base >=4.8`. I wonder why the dependency is fixed to that range, though.

**Comment by egnwd** [comment]
As far as I can remember this was added automatically by cabal when I set up the project. There should be no issue with removing the upper bound.

Just to make aware, I made this project as something that would be fairly experimental. I am going to be updating it shortly with some additional parsing functionality to the exposed library. The executable should remain as it is though.

**Comment by domoritz** [comment]
Thanks for making the tool available. If you plan to work on it, I'd love to see support for optimal answer sets. I'm going to close this issue.

**Comment by egnwd** [comment]
No worries, I've made a branch [`optimisation`](https://github.com/egnwd/pingo/tree/optimisation). It's not fully tested yet, and it builds on some new updates. When I have some time I'll look at it properly and merge it in. If you run into any issues please let me know.
